---
- name: "Set the root dir"
  set_fact:
    root_dir: "{{ playbook_dir }}/../"
  tags:
    - grunt


- name: "Give your system AIDS"
  npm:
    name: "{{ item }}"
    state: "present"
    global: yes
  with_items:
    - "grunt"
    - "grunt-cli"
  become: yes
  run_once: true
  delegate_to: localhost
  tags:
    - grunt


- name: "Install npm dependencies (if npm is working at the time)"
  npm:
    path: "{{ root_dir }}"
  run_once: true
  delegate_to: localhost
  tags:
    - grunt


- name: "Leverage your new-found AIDS to build assets"
  command:
    "grunt build"
  args:
    chdir: "{{ root_dir }}"
  run_once: true
  delegate_to: localhost
  tags:
    - grunt


- name: "tar up cancer and AIDS-riddled assets"
  command:
    "{{ item }}"
  args:
    chdir: "{{ root_dir }}"
  with_items:
    - "tar czf node_modules.tgz node_modules/"
    - "tar czf static_dist.tgz static/dist"
  run_once: true
  delegate_to: localhost
  tags:
    - grunt


- name: "Put .tgz's on the host (this takes a while b/c npm is a joke)"
  unarchive:
    src: "{{ root_dir }}/{{ item }}"
    dest: "{{ checkout_location }}"
  with_items:
    - "node_modules.tgz"
    - "static_dist.tgz"
  tags:
    - grunt
  notify:
    - restart pokemaps


- name: "Remove that shiz before it spreads"
  file:
    path: "{{ root_dir }}/{{ item }}"
    state: absent
  with_items:
    - "node_modules.tgz"
    - "static_dist.tgz"
  run_once: true
  delegate_to: localhost
