# ansible-playbook manage_ec2.yml -i localhost --vault-password-file=./.vaultfile

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Set instance state
      ec2:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        region: "us-east-1"
        state: "{{ state | default('running') }}"
        instance_tags:
          Name: pokemaps
      register: ec2

    - name: Wait for SSH to come up
      local_action: wait_for
                    host={{ item.public_ip }}
                    port=22
                    state=started
      with_items: "{{ ec2.instances }}"
      when: "state == 'restarted' or state == 'running'"
